### ISSUE TITLE
I am very interested This Game,But How make it work?

### ISSUE THREAD

**Issue by llsifac** [641i130/harasho#2]
Hello,Thanks for your good work,
is this used on a normal pc with the Dump llsifas data or a taito type zero?

I would like to play it on online version,that can save date and also can play more songs and more difficulty and get more costumes,
for now I just can only play the difficulty of EXTREME,because of the guest mode only can play two songs each time.
I have the real hardware can play it offline by renaming the nesicaserver.exe in original hdd.
could you tell me the steps please?
Thanks in advance.

**Comment by 641i130** [comment]
Hello, this server does not work currently.
You'll want this one:

https://github.com/asesidaa/LLServer

The team is extremely close to getting save data 'working'. It functions fully with event mode (which unlocks all songs).

Use this as a guide (it is incomplete):
https://carette.codeberg.page/ll-hax-docs/
